### ISSUE TITLE
cummeRbund error

### ISSUE THREAD

**Issue by sumitra20** [johanzi/RNA-seq_pipeline#1]
hi @johanzi ,

i've been running the cufflink-cuffdiff-cummerbund pipeline for my analysis involving 2 groups (hyp-has 2 replicate, lyp-only one sample). Everything went well up to cuffdiff but when i tried plotting on cummerbund i end up with error everytime i try to plot (csScatter, csDensity, heatmap) only for the significant genes . Error says that: error:unable to find an inherited method for function 'csScatter' for signature '"data.frame". Im trying to understand where im going wrong, any help will be much appreciated.

#cuffdiff command 
`cuffdiff -o ./cuffdiff_output_testdata -L hyp,lyp -p 8 -b Oryza_indica.ASM465v1.dna_sm.toplevel.fa ./cuffmerge_output/merged.gtf /R32P1_R4_ensembl_GTF_tophat_out/accepted_hits.bam,/R32P3_R4_ensembl_GTF_tophat_out/accepted_hits.bam /R34P4_R_ensembl_GTF_tophat_out/accepted_hits.bam`

#cummerbund
```
> cuffdiff_data
CuffSet instance with:
	 2 samples
	 56245 genes
	 88197 isoforms
	 76870 TSS
	 40736 CDS
	 56245 promoters
	 76870 splicing
	 39033 relCDS
> gene_diff <- diffData(genes(cuffdiff_data))
> sig_gene_diff <- subset(gene_diff, (significant == 'yes'))
> nrow(sig_gene_diff)
[1] 347
> csScatter(sig_gene_diff, 'hyp', 'lyp')
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'csScatter' for signature '"data.frame"'

```

**Comment by johanzi** [comment]
Is your object "sig_gene_diff " an object of class ('CuffData','CuffFeatureSet') after subsetting? Maybe the subset function comes from another package and generates a data.frame object?

Try this to see and check if your `sig_gene_diff` object is of the same class as `genes`:
```
a<-readCufflinks(system.file("extdata", package="cummeRbund")) #Create CuffSet object from sample data
	genes<-a@genes #Create CuffData object for all genes
	s<-csScatter(genes,'hESC','Fibroblasts',smooth=TRUE) #Create plot object
	s #render plot object
```
